<!-- Modal -->
<div class="modal fade" id="termsConditionModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title" id="exampleModalLabel">iWellness Terms and Condition</h2>
        </div>

        <div class="modal-body">
            <div class="container" style="overflow-x:hidden;overflow-y:auto;">
                <p class="w-full">
                PLEASE READ THESE TERMS OF USE AND THE PRIVACY POLICY, BEFORE USING THIS WEBSITE OR PURCHASING ANY PRODUCT OR SERVICES FROM IWELLNESS HEALTH AND BEAUTY TRADING

                <br><br>These Terms of Use are an agreement (the “Agreement”) between iWellness health and beauty Trading (“iWellness health and beauty Trading,” the “Company”, “we” or “us”) and you "you" or "User"). This Agreement sets forth the legal terms and conditions governing your use of this website (the "Site") and your purchase and/or use of any iWellness goods, services (collectively referred to hereinafter as, “Offerings”). This Agreement also provides information on how to become an iWellness Independent Distributor or iWellness Preferred Member.
                <br>Your use of the Site and all information, data, text, software, information, images, sounds or other materials contained therein, or your use or purchase of any other Offerings confirms your unconditional agreement to be bound by this Agreement and is subject to your continued compliance with the terms and conditions of this Agreement. If you do not agree to be bound by this Agreement, do not access or otherwise use the Site or participate in any of the Offerings.
                
                <br><br>The information and features included in this Site are subject to change at any time without notice. By accessing or linking to this Site (to the extent linking is permissible), you assume the risk that the information on this Site may be changed or removed.
                <br><br><h4>1. MODIFICATIONS</h4>
                <br>We reserve the right at any time to:
                Change the terms and conditions of this Agreement;
                Enhance, add to, modify or discontinue the Site or other Offerings, or any portion of the Site or other Offerings, at any time in our sole discretion.
                From time to time, we reserve the right, in our sole discretion, to modify, update, add to, discontinue, remove, revise or otherwise change any portion of this Agreement, in whole or in part, at any time. For changes to this Agreement that we consider to be material, we will place a notice on the Site by revising the link on the homepage to read substantially as "Updated Terms of Use" for a reasonable amount of time. If you provide information to us, access or use the Site or participate in any Offering in any way after this Agreement has been changed, you will be deemed to have read, understood and consented to and agreed to such changes. The most current version of this Agreement will be available on the Site and will supersede all previous versions of this Agreement.
                <br><br><h4>2. ACCESS</h4>
                <br>You must obtain access to the Internet and pay any service fees associated with such access to use the Site. In addition, you must provide all equipment necessary for you to access the Internet. You are and will remain solely responsible for the purchase, hookup, installation, loading, operation and maintenance of any hardware, software, telephone (cable or other) service, and the Internet access service to your personal computer and for all related costs. You are solely responsible for scanning your hardware and software for computer viruses and other related problems before you use them. We expressly disclaim, subject to Section 16 of this Agreement, any liability or responsibility for any errors or failures relating to the malfunction or failure of your hardware or software in connection with the use of the Site or Offerings.
                <br><br><h4>3. ELIGIBILITY</h4>
                <br>You represent and warrant that you are eighteen (18) years of age or older, or if you are under the age of eighteen (18) you are at least accessing the Site with the knowledge and consent of your parent or legal guardian, who will also be deemed to have agreed to this Agreement. Certain features on this Site (including, but not limited to, user registration) and certain Offerings may be subject to heightened age and/or other eligibility requirements.
                <br><br><h4>4. BECOMING AN iWELLNESS PREFERRED MEMBER OR IWELLNESS INDEPENDENT DISTRIBUTOR</h4>
                <br>iWellness health and beauty trading products and services are sold through iWellness network of Independent Distributors. To purchase iWellness goods or services, you do not have to become a Distributor. Instead, you can purchase products from a Distributor or become an iWellness Preferred Member. If you are interested in purchasing products from a Distributor or becoming a Preferred Member, please see the Product section or start activating your account to see the benefits of being a member.
                <br><br><h4>5. REFUND POLICIES</h4>
                <br>iWellness do not allow any refund from activation or product purchases. However, iWellness allow refunds if you just cash-in the amount and not have yet use it for activation or product purchases. Some documents may be required, such as but not limited to proof of receipt or picture of cash-in request, before the refund will be approved. It may take 7- 10 days before you receive your refund.
                <br><br><h4>6. INFORMATION AND PRIVACY</h4>
                <br>If you provide information to the Site, you agree to provide accurate, current and complete information where requested and you agree to maintain and update such information as appropriate. We will use and maintain personal information that we collect through the Site in accordance with our Privacy Policy.
                <br><br><h4>7. USER FORUMS, GROUP CHATS, FACEBOOK PAGE AND GROUPS</h4>
                <br>Forums, bulletin boards, chat rooms or other interactive areas that are or may be offered on the Site ("User Forums") are provided to give users a forum to express their opinions and share their ideas and information. The individual who posts content in the User Forums ("Community Content") is responsible for the reliability, accuracy, and truthfulness of such content, and we have no control over the same. Additionally, we have no control over whether any such posted material is of a nature that users will find offensive, distasteful or otherwise unacceptable and expressly disclaim any responsibility for such material.
                We do not and cannot review every message posted by users in the User Forums, and are not responsible for the content of these messages or the views or opinions expressed by the users of the User Forums. Information disclosed in the User Forums is by design revealed to the public. We reserve the right, but are not obligated, to delete, move or edit content, in whole or in part, submitted by you to the Site for any reason in our sole discretion. In addition, we may delete, move, edit or disclose the contents of messages when it is required to do so by law or in a good faith belief that such action is necessary to protect and defend our rights and property or to protect the safety of our users or the public. In no event do we assume any obligation to monitor the User Forums or remove any specific material.
                You understand that the uploading to and/or posting of any Community Content in any User Forum shall not be subject to any obligation of confidentiality on the part of Company, and we shall not be liable, subject to Section 16 of this Agreement, for any use or disclosure of any Community Content.
                (a) Restrictions on Use
                In consideration for your use of the User Forums and functionality, you agree to comply with the "Community Guidelines" set forth below. Without limiting our other rights and remedies, individuals who violate the following Community Guidelines may, at our sole discretion, be permanently banned from using the Site: harass, stalk or otherwise abuse another user;
                transmit, post, send, upload, distribute, submit or otherwise make available any content that suggests that participating in the iWellness opportunity will result in a lavish lifestyle, including the following, or any substantially similar images: opulent mansions, private helicopters, jets, or yachts; or exotic automobiles;
                transmit, post, send, upload, distribute, submit or otherwise make available any content that is false, harmful, threatening, abusive, tortious, defamatory, libelous, disparaging (including disparaging of iWellness health and beauty Trading), vulgar, obscene, pornographic or that promotes violence, racial hatred, terrorism or illegal acts, or is otherwise objectionable (as determined by us in our sole discretion);
                transmit, post, send, upload, distribute, submit or otherwise make available any content which is or could be detrimental to or which may otherwise diminish, damage or weaken the reputation or image of iWellness health and beauty trading, its products, Distributors, trademarks, trade names or goodwill;
                transmit, post, send, upload, distribute, submit or otherwise make available any content that is unlawful or infringes, violates or misappropriates any patent, trademark, trade identity right, trade secret, publicity right, privacy right, copyright or any other intellectual property or any other rights of any third party;
                transmit, post, send, upload, distribute, submit or otherwise make available any viruses, Trojan horses or other harmful, disruptive or destructive files or material that interferes with any third party's use and enjoyment of the Site;
                impersonate any person or entity, or otherwise disguise the origin of any content transmitted through the Site or to iWellness, including forging any TCP/IP packet header or any part of the header information in any transmission to the Site for any reason;
                transmit, post, send, upload, distribute, submit or otherwise make available through the Site any personal advertising, junk mail, spam, chain letters, pyramid schemes or offer for sale of any products or services, except in areas, if any, specifically designated for such purposes; or
                violate any applicable local, state, federal or international law, rule or regulation.
                participate in any part of the Site if you are under the age of 18.
                transmit, post, send, upload, distribute, submit or otherwise make available through the Site any content containing any solicitation of funds, promotion, advertising, or solicitation for goods or services. You also hereby acknowledge that you are prohibited from soliciting other guests to join or become members of any commercial online service or other organization.
                collect or harvest the information of any user or otherwise access the Site using automated means (including but not limited to harvesting bots, robots, spiders or scrapers).
                “frame”, “mirror” or “deep link” any part of the Site or other Offerings without our prior written authorization.
                link to any page within the Site or other Offerings from any web site or web page that makes any claims as to the curative or health enhancing powers of any substance, whether or not such substance is produced, marketed, sold or distributed by us.
                We do not endorse the Community Content in the User Forums and specifically disclaim any responsibility or liability, subject to Section 16 of this Agreement, to any person or entity (including, without limitation, persons who may use or rely on such material) for any loss, damage (whether actual, consequential, punitive or otherwise), injury, claim, liability or other cause of any kind or character based upon or resulting from any Community Content provided through a User Forum. By posting or uploading Community Content to any User Forum or submitting any other Community Content to us, you automatically grant (or warrant that the owner of such rights has expressly granted) us a perpetual, worldwide, royalty-free, irrevocable, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate, sub-license, create derivative works from and distribute such materials or incorporate such Community Content into any form, medium, or technology now known or hereafter devised throughout the universe in perpetuity. In addition, you warrant that the content as uploaded or posted by you does not violate any person's so-called publicity rights or "moral rights" or other similar or analogous rights under any applicable laws in any country or region of the world.
                <br><br><h4>8. USE OF E-MAIL ADDRESSES PROVIDED BY THE SITE</h4>
                <br>When using any e-mail address, or e-card/e-message functionality, provided to you on or through the Site or other Offerings, you agree to use such email address in accordance with all applicable laws and not to transmit to any person or entity:
                any content that violates the Community Guidelines set forth above with respect to the User Forums or that is unlawful, fraudulent, threatening, abusive, libellous, defamatory, vulgar, obscene, harmful, harassing, tortious, invasive of another’s privacy, hateful, or is racially, ethnically or otherwise objectionable, or is subject to an agreement of confidentiality, or infringes upon our or any third party’s intellectual property or other rights;
                any non-public information about any company;
                any trade secret; or	
                any computer code, files or programs (for example, a computer virus) designed to interrupt, destroy, compromise the security of or limit the functionality of any device.
                Spamming is strictly prohibited. Spam is defined for this purpose as sending an unsolicited message to any persons, entities, newsgroups, forums, e-mail lists or other groups or lists unless prior authorization has been obtained from the e-mail recipient which explicitly permits sending e-mail communication to them, or unless a business or personal relationship has already been established with the e-mail recipient. IF YOU ARE “SPAMMED” BY SOMEONE WHO IS SELLING OR DESCRIBING IWELLNESS PRODUCTS OR BUSINESS OPPORTUNITY, PLEASE CONTACT US PROMPTLY.
                The use of false headers in e-mails or falsifying, forging or altering the origin of any e-mail in connection with iWellness and/or its products and services is prohibited.
                If a person or entity indicates that they do not want to receive e-mail, you agree not to send e-mail to such person or entity. If a person initially agrees to receive e-mail, but later asks to stop receiving e-mail, you must abide by that request.
                .
                <br><br><h4>9. OUR PROPRIETARY RIGHTS</h4>
                <br>This Site and all of the content it contains, or may in the future contain, including but not limited to articles, opinions, other text, directories, guides, photographs, illustrations, images, video and audio clips and advertising copy, as well as the trademarks, copyrights, logos, domain names, code, trade names, service marks, patents and any and all copyrightable material (including source and object code) and/or any other form of intellectual property (collectively, the "Material") are owned by or licensed to us or other authorized third parties and are protected from unauthorized use, copying and dissemination by copyright, trademark, publicity and other laws and by international treaties. Unless expressly permitted in writing by us, you shall not capture, reproduce, perform, transfer, sell, license, modify, create derivative works from or based upon, republish, reverse engineer, upload, edit, post, transmit, publicly display, frame, link, distribute, or exploit in whole or in part any of the Material. Nothing contained in this Agreement or on the Site should be construed as granting, by implication, estoppel or otherwise, any license or right to use any Material in any manner without the prior written consent of us or such third party that may own the Material or intellectual property displayed on the Site. UNAUTHORIZED USE, COPYING, REPRODUCTION, MODIFICATION, PUBLICATION, REPUBLICATION, UPLOADING, FRAMING, DOWNLOADING, POSTING, TRANSMITTING, DISTRIBUTING, DUPLICATING OR ANY OTHER MISUSE OF ANY OF THE MATERIAL IS STRICTLY PROHIBITED. Any use of the Material other than as permitted by this Agreement will, subject to Section 16 of this Agreement, constitute a violation of this Agreement and may constitute copyright and/or patent infringement. You agree not to use the Material for any unlawful purposes and not to violate our rights or the rights of others. You agree not to interfere or permit any third party to interfere with the normal processes or use of the Site by other users, including without limitation by attempting to access administrative areas of the Site. You are advised that we will aggressively enforce our rights to the fullest extent of the law. We may add, change, discontinue, remove or suspend any of the Material at any time, without notice and without liability. iWellness, our logo, and the name of the products produced, marketed, sold or distributed by the iWellness, are trademarks and/or service marks of iWellness health and beauty Trading. All other trademarks, service marks, and logos used on the Site or other Offerings are the trademarks, service marks or logos of their respective owners.
                <br>10. MEMBERSHIP AND REGISTRATION
                <br>Certain areas of the Site may require registration or may otherwise ask you to provide information to participate in certain features or to access certain content. The decision to provide this information is purely voluntary and optional; however, if you elect not to provide such information, you may not be able to access certain content or participate in certain features of the Site.
                If you register with the Site, you agree to accept responsibility, subject to Section 16 of this Agreement, for all activities that occur under your account, email or password, if any, and agree you will not sell, transfer or assign your membership, any membership rights or any Site issued email address or e-card/e-message functionality. You are responsible for maintaining the confidentiality of your password, if any, and for restricting access to your computer so that others may not access the password protected portion of the Site or your Site issued email account using your name in whole or in part. We may, in our sole discretion, and at any time, with or without notice, terminate your access and membership, for any reason or no reason at all.
                <br><br><h4>11. PROMOTIONS</h4>
                <br>This Site may contain sweepstakes, contests or other promotions that require you to send material or information about yourself. Please note that sweepstakes, contests or promotions offered via the Site may be, and often are, governed by a separate set of rules that, in addition to describing such sweepstakes, contest or promotion, may have eligibility requirements, such as certain age or geographic area restrictions, terms and conditions governing the use of material you submit, and disclosures about how your personal information may be used. It is your responsibility to read such rules to determine whether or not you want to and are eligible to participate, register and/or enter. By entering any such sweepstakes, contest or other promotion, you agree to comply with abide by such rules and the decisions of the sponsor(s) identified therein, which shall be final and binding in all respects.
                <br><br><h4>12. TERMINATION MODIFICATION</h4>
                <br>We will determine, subject to Section 16 of this Agreement, your compliance with this Agreement in our sole discretion and our decision shall be final and binding. Any violation of this Agreement may result in restrictions on your access to all or part of the Site and may be referred to law enforcement authorities. No waiver of any of this Agreement shall be of any force or effect unless made in writing and signed by a duly authorized officer of iWellness health and Beauty Trading. We reserve the right to modify or discontinue this Site, or any portion thereof without notice to you or any third party. Upon termination of your membership, distributorship, or access to the Site, or upon demand by iWellness Health and Beauty Trading, you must destroy all materials obtained from this Site and all related documentation and all copies and installations thereof. You are advised that we will aggressively enforce our rights to the fullest extent of the law.
                If any provision of this Agreement is found to be invalid by any court having competent jurisdiction, the invalidity of such provision will not affect the validity of the remaining provisions of this Agreement, which will remain in full force and effect. The section titles in this Agreement are for your convenience only and do not have any legal or contractual effect.
                <br><br><h4>21. Email us</h4>
                <br>If you have any questions, comments or concerns about our Site, any Offerings or this Agreement, you may email us at iWellnesshnbtrading@gmail.com

                </p>
            </div>

            <div class="w-full pt-4 pb-0 text-right mt-4">
                <button type="button" class="btn btn-secondary btn--terms" data-checkbox="false" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-info btn--terms" data-checkbox="true">I Agree to Terms and Conditions</button>
            </div>
        </div>
      </div>
    </div>
</div>